# Generated by Django 4.2.3 on 2023-07-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.CharField(choices=[('Проектирование', 'Проектирование'), ('Разработка', 'Разработка'), ('Анализ', 'Анализ'), ('Исправление ошибки', 'Исправление ошибки'), ('Тестирование', 'Тестирование'), ('Другое', 'Другое')], max_length=20)),
                ('executor', models.CharField(default='user', max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
