# Generated by Django 4.2.3 on 2023-07-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor_costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labor',
            options={'ordering': ['-date']},
        ),
    ]
