# Generated by Django 4.2.3 on 2023-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='admin',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
