# Generated by Django 4.2.3 on 2023-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='perfomance_status',
            field=models.CharField(default='Not completed', max_length=15),
        ),
    ]
