# Generated by Django 4.2.3 on 2023-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_perfomance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='perfomance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='perfomance_status',
            field=models.CharField(choices=[('Выполнен', 'Выполнен'), ('Не выполнен', 'Не выполнен'), ('Отклонен', 'Отклонен')], default='Не выполнен', max_length=15),
        ),
    ]
