# Generated by Django 4.2.3 on 2023-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='admin',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
