# Generated by Django 4.2.3 on 2023-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projects_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='perfomance_date',
            field=models.DateField(blank=True, default='-', null=True),
        ),
    ]
