# Generated by Django 4.2.3 on 2023-07-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projects_perfomance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='perfomance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
