# Generated by Django 4.2.3 on 2023-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='perfomance_date',
            field=models.DateField(blank=True, default='-', null=True),
        ),
    ]
