# Generated by Django 4.2.3 on 2023-07-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_perfomance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='perfomance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
