# Generated by Django 4.2.3 on 2023-07-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_perfomance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='perfomance_date',
            field=models.DateField(blank=True, default='-', null=True),
        ),
    ]
